"""CodeWiki Agent for auto-generating comprehensive codebase documentation and class/function Wiki hubs."""

import os
import ast
import time
from pathlib import Path


class CodeWikiAgent:
    """CodeWiki Agent for scanning codebases and generating interactive Markdown documentation hubs."""

    def __init__(self):
        self.output_dir = Path.home() / ".bishu" / "codewiki"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_codewiki(self, repo_path: str = None) -> str:
        """Scan repository Python files and generate a structured CodeWiki Markdown Documentation Hub."""
        target_path = Path(repo_path) if repo_path else Path.cwd()
        if not target_path.exists():
            return f"Path '{repo_path}' not found for CodeWiki generation."

        print(f"[CodeWikiAgent] Generating CodeWiki for repository '{target_path.name}'...")

        wiki_modules = []
        py_files = list(target_path.rglob("*.py"))

        for p in py_files[:25]: # Scan up to 25 core files
            if ".venv" in str(p) or "venv" in str(p) or "__pycache__" in str(p):
                continue
            try:
                with open(p, "r", encoding="utf-8", errors="ignore") as f:
                    tree = ast.parse(f.read(), filename=p.name)

                classes = [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
                functions = [node.name for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
                
                docstring = ast.get_docstring(tree) or "No module docstring."

                wiki_modules.append({
                    "file": p.relative_to(target_path),
                    "docstring": docstring,
                    "classes": classes,
                    "functions": functions
                })
            except Exception:
                pass

        # Build Markdown Wiki Hub
        wiki_lines = [
            f"# CODEWIKI DOCUMENTATION HUB: {target_path.name.upper()}\n",
            f"*Generated by Laalaa CodeWiki Agent on {time.strftime('%Y-%m-%d %H:%M:%S')}*\n",
            f"**Total Modules Documented**: {len(wiki_modules)}\n\n",
            "---",
            "## 📚 MODULE ARCHITECTURE INDEX\n"
        ]

        for mod in wiki_modules:
            wiki_lines.append(f"### 📄 `{mod['file']}`")
            wiki_lines.append(f"> {mod['docstring']}\n")
            if mod['classes']:
                wiki_lines.append(f"- **Classes**: " + ", ".join([f"`{c}`" for c in mod['classes']]))
            if mod['functions']:
                wiki_lines.append(f"- **Functions**: " + ", ".join([f"`{f}`" for f in mod['functions'][:10]]))
            wiki_lines.append("\n")

        wiki_content = "\n".join(wiki_lines)
        filename = f"CodeWiki_{target_path.name}_{int(time.time())}.md"
        wiki_file = self.output_dir / filename

        with open(wiki_file, "w", encoding="utf-8") as f:
            f.write(wiki_content)

        return f"📚 CodeWiki Documentation Hub generated for '{target_path.name}' ({len(wiki_modules)} modules documented) and saved to: {wiki_file.name}"
