"""AI Website Template Builder for HTML5 Canvas, CSS Grid Layouts, and Tailwind JS Integration."""

import os
import time
import webbrowser
from pathlib import Path


class WebTemplateBuilder:
    """AI Website Builder generating responsive HTML5 Canvas, CSS Grid, and Tailwind CSS/JS templates."""

    def __init__(self, ai_engine=None):
        self.ai = ai_engine
        self.output_dir = Path.home() / ".bishu" / "web_templates"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def build_template(self, prompt: str) -> str:
        """Generate full responsive HTML5, CSS Grid & Tailwind CSS/JS website template."""
        print(f"[WebTemplateBuilder] Generating Website Template for: '{prompt}'...")

        filename = f"Website_{int(time.time())}.html"
        file_path = self.output_dir / filename

        html_content = self._generate_html5_template(prompt)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        # Open in web browser
        try:
            webbrowser.open(str(file_path))
        except Exception:
            pass

        return f"Responsive HTML5 Website Template for '{prompt}' generated with CSS Grid & Tailwind JS and saved to: {file_path}"

    def _generate_html5_template(self, prompt: str) -> str:
        """Construct responsive HTML5, CSS Grid, Canvas, and Tailwind template."""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{prompt.title()} - Generated by Laalaa AI</title>
    <!-- Tailwind CSS Integration -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        /* CSS Grid Custom Layout */
        .grid-layout {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1.5rem;
        }}
    </style>
</head>
<body class="bg-slate-900 text-white font-sans antialiased min-h-screen">
    <!-- Navigation -->
    <nav class="p-6 bg-slate-800 border-b border-cyan-500/30 flex justify-between items-center">
        <h1 class="text-2xl font-bold text-cyan-400">{prompt.title()}</h1>
        <span class="text-sm bg-cyan-900/60 text-cyan-300 px-3 py-1 rounded-full border border-cyan-500">Built with Laalaa AI</span>
    </nav>

    <!-- Hero Section -->
    <section class="py-16 text-center max-w-4xl mx-auto px-6">
        <h2 class="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500 mb-4">{prompt.title()}</h2>
        <p class="text-slate-300 text-lg mb-8">Modern responsive Web App template featuring HTML5 Canvas, CSS Grid, and Tailwind CSS.</p>
        
        <!-- Interactive HTML5 Canvas Animation -->
        <canvas id="heroCanvas" class="w-full h-64 rounded-xl border border-cyan-500/40 bg-slate-950 mb-10"></canvas>
    </section>

    <!-- CSS Grid Feature Section -->
    <section class="max-w-6xl mx-auto px-6 pb-20">
        <h3 class="text-2xl font-bold text-cyan-400 mb-6">Key Platform Features</h3>
        <div class="grid-layout">
            <div class="p-6 bg-slate-800/80 rounded-xl border border-slate-700">
                <h4 class="text-xl font-bold text-cyan-300 mb-2">CSS Grid Layouts</h4>
                <p class="text-slate-400 text-sm">Flexible grid system adapting smoothly across mobile and desktop devices.</p>
            </div>
            <div class="p-6 bg-slate-800/80 rounded-xl border border-slate-700">
                <h4 class="text-xl font-bold text-cyan-300 mb-2">Tailwind JS</h4>
                <p class="text-slate-400 text-sm">Utility-first CSS with dynamic styling and reactive components.</p>
            </div>
            <div class="p-6 bg-slate-800/80 rounded-xl border border-slate-700">
                <h4 class="text-xl font-bold text-cyan-300 mb-2">HTML5 Canvas Graphics</h4>
                <p class="text-slate-400 text-sm">Hardware-accelerated 2D graphics and real-time interactive animations.</p>
            </div>
        </div>
    </section>

    <!-- Interactive Canvas JS Script -->
    <script>
        const canvas = document.getElementById('heroCanvas');
        const ctx = canvas.getContext('2d');
        canvas.width = canvas.offsetWidth;
        canvas.height = canvas.offsetHeight;

        let particles = [];
        for(let i = 0; i < 40; i++) {{
            particles.push({{
                x: Math.random() * canvas.width,
                y: Math.random() * canvas.height,
                radius: Math.random() * 3 + 1,
                vx: (Math.random() - 0.5) * 1.5,
                vy: (Math.random() - 0.5) * 1.5
            }});
        }}

        function animate() {{
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = '#00f0ff';
            particles.forEach(p => {{
                ctx.beginPath();
                ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
                ctx.fill();
                p.x += p.vx;
                p.y += p.vy;
                if(p.x < 0 || p.x > canvas.width) p.vx *= -1;
                if(p.y < 0 || p.y > canvas.height) p.vy *= -1;
            }});
            requestAnimationFrame(animate);
        }}
        animate();
    </script>
</body>
</html>
"""
